### ISSUE TITLE
Feature request: Namespace support for view-secret

### ISSUE THREAD

**Issue by drzero42** [ahmetb/kubectl-extras#3]
Great plugins in here! :D
It would be awesome if the view-secret plugin could support namespaces, so I can print out a decoded secret from a namespace other than the one currently set in the context.

**Comment by ahmetb** [comment]
@drzero42 ideally plugins should support `-n`/`--namespace` flags.

Most plugins you see here are some of the first plugins in the world. I should probably rewrite them at some point.
