### ISSUE TITLE
[mtail] -  add support for pods with multiple containers

### ISSUE THREAD

**Issue by grzesuav** [ahmetb/kubectl-extras#5]
Often pods have more than one container. In this case mtails returns :
```
+ kubectl logs --follow prometheus-main-0 --tail=10
+ kubectl logs --follow prometheus-main-1 --tail=10
Error from server (BadRequest): a container name must be specified for pod prometheus-main-1, choose one of: [prometheus prometheus-config-reloader rules-configmap-reloader]
Error from server (BadRequest): a container name must be specified for pod prometheus-main-0, choose one of: [prometheus prometheus-config-reloader rules-configmap-reloader]

```

solution :
additional `-c` parameter to specify container would solve the case

**Comment by ahmetb** [comment]
@grzesuav would you like to contribute a patch? 
For the record, to mimic `kubectl logs` command, `-c` as well as `--container` ideally should be implemented.

**Comment by grzesuav** [comment]
Could try, however I am not very advanced in bash scripting ;)

**Comment by ahmetb** [comment]
No problem, thanks for reporting this.
I haven't been able to revisit this plugin in a while. I'll find a way to make this better.

**Comment by grzesuav** [comment]
Got an idea while googling, will try to prepare sth before weekend

**Comment by grzesuav** [comment]
https://github.com/ahmetb/kubectl-extras/pull/6/

**Comment by grzesuav** [comment]
Actually compared to automatic bash arg generator and decided  to use it, and slightly adjust the code
